name: app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory to app
        run: cd app
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory to app
        run: cd app
      - name: Install dependencies
        run: npm ci
      - name: Lint app
        run: npm run lint
